SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.COUNT) AS TOTAL_SALES
FROM AUTHOR a
JOIN BOOK b ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN (SELECT BOOK_ID, SUM(SALES) AS COUNT FROM BOOK_SALES
      WHERE SALES_DATE LIKE "2022-01%"
      GROUP BY BOOK_ID) s
ON b.BOOK_ID = s.BOOK_ID
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;