SELECT p.PRODUCT_CODE, (p.PRICE * o.SALES_AMOUNT) AS SALES
FROM PRODUCT p
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
      FROM OFFLINE_SALE
     GROUP BY PRODUCT_ID) o ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;