WITH joined_2021 AS (
  SELECT USER_ID
  FROM USER_INFO
  WHERE YEAR(JOINED) = 2021
),
sales_2021_users AS (
  SELECT DISTINCT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    USER_ID
  FROM ONLINE_SALE
  WHERE USER_ID IN (SELECT USER_ID FROM joined_2021)
),
user_counts AS (
  SELECT 
    YEAR,
    MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
  FROM sales_2021_users
  GROUP BY YEAR, MONTH
)

SELECT 
  u.YEAR,
  u.MONTH,
  u.PURCHASED_USERS,
  ROUND(u.PURCHASED_USERS / (SELECT COUNT(*) FROM joined_2021), 1) AS PUCHASED_RATIO
FROM user_counts u
ORDER BY u.YEAR, u.MONTH;