WITH RECURSIVE generation_cte AS (
  SELECT ID, PARENT_ID, 1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
  FROM ECOLI_DATA e
  JOIN generation_cte g ON e.PARENT_ID = g.ID
)

SELECT 
  COUNT(*) AS COUNT,
  g.GENERATION
FROM generation_cte g
LEFT JOIN ECOLI_DATA c ON g.ID = c.PARENT_ID
WHERE c.ID IS NULL
GROUP BY g.GENERATION
ORDER BY g.GENERATION;