SELECT g.USER_ID, g.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER g ON b.WRITER_ID = g.USER_ID
WHERE b.STATUS = "DONE"
GROUP BY g.USER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;