SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
     GROUP BY FISH_TYPE) m ON i.FISH_TYPE = m.FISH_TYPE AND i.LENGTH = m.LENGTH 
ORDER BY i.ID;